<?php

/*
|--------------------------------------------------------------------------
| Corral account settings
|--------------------------------------------------------------------------
| Lists from the original Corral account page: flags, the two action menus,
| products, note categories and actions, priorities, queues, reward offers
| and email templates. The account page and its forms are built from these.
*/

return [

    'flags' => [
        'VIP - PUC Complaint', 'VIP - Critical Care', 'VIP - Payment Arrangement', 'VIP - Deferred Payment Plan',
        'VIP - Inadvertent Gain', 'VIP - Inadvertent Loss', 'VIP - Billing Error', 'VIP - Friends & Family', 'VIP - Other',
        'SOLAR CUSTOMER', 'Returned Mail', 'Fraudulent Order', 'Multiple Enrollments', 'Order has been cancelled manually',
    ],

    // Banner shown at the top of the account when the flag is present: [title, message]
    'flag_banners' => [
        'SOLAR CUSTOMER' => ['SOLAR CUSTOMER', 'Handle with care!'],
        'VIP - Friends & Family' => ['Friends and Family', 'This customer is a Friends and Family customer. Please escalate to the back office!'],
        'VIP - PUC Complaint' => ['PUC Complaint', 'Open PUC complaint. Escalate to a supervisor before making changes.'],
        'VIP - Critical Care' => ['Critical Care', 'Critical care customer. Do not disconnect.'],
        'Fraudulent Order' => ['Fraudulent Order', 'Verify identity before discussing the account.'],
    ],

    /*
    | Account actions ("-- Status --" and "-- Customer Service --" menus).
    | fields: name => [label, type, options?]. perm: extra right needed.
    | Each one is handled by App\Services\AccountActions::<camelCase key>().
    */
    'actions' => [
        'status' => [
            'credit-run' => ['Credit - Run Credit', []],
            'credit-max-deposit' => ['Credit - Give Max Deposit', []],
            'credit-waive-deposit' => ['Credit - Waive Deposit', ['reason' => ['Reason', 'text']]],
            'send-to-market' => ['Status - Send to Market', ['date' => ['Requested start', 'date']]],
            'temp-disconnect' => ['Status - Temp Disconnect', ['date' => ['Disconnect date', 'date']]],
            'disconnect' => ['Status - Disconnect', ['date' => ['Disconnect date', 'date']]],
            'reconnect' => ['Status - Reconnect', []],
            'move-out' => ['Status - Move Out', ['date' => ['Move-out date', 'date']]],
            'cancel-order' => ['Status - Cancel Order', ['reason' => ['Reason', 'text']]],
            'delete-order' => ['Status - Delete Order', [], 'delete'],
            'winback' => ['Status - Winback', []],
            'clear-exceptions' => ['Misc - Clear Current Exceptions', []],
            'repair-plan' => ['Misc - Repair Plan', []],
            'undo-last-plan' => ['Misc - Undo Last Plan', []],
            'add-order' => ['Misc - Add Order', []],
        ],
        'service' => [
            'make-payment' => ['Billing - Make Payment', ['amount' => ['Amount ($)', 'money'], 'method' => ['Payment method', 'method']]],
            'add-bill-credit' => ['Billing - Add Bill Credit', ['amount' => ['Amount ($)', 'money'], 'description' => ['Description', 'text']]],
            'balance-adjustment' => ['Billing - Add Balance Adjustment Payment', ['amount' => ['Amount ($)', 'money'], 'description' => ['Reason', 'text']]],
            'payment-arrangement' => ['Billing - Payment Arrangement', ['installments' => ['Installments', 'number'], 'date' => ['First due date', 'date']]],
            'deferred-payment-plan' => ['Billing - Deferred Payment Plan', ['installments' => ['Installments', 'number'], 'date' => ['First due date', 'date']]],
            'transfer-payments' => ['Billing - Transfer Payments', ['payment' => ['Payment', 'payment'], 'account' => ['To account #', 'text']]],
            'transfer-stars' => ['Billing - Transfer Stars', ['stars' => ['Stars', 'number'], 'account' => ['To account #', 'text']]],
            'balanced-billing' => ['Billing - Balanced Billing', []],
            'transfer-service' => ['Plan - Transfer Service', ['street' => ['New street', 'text'], 'city' => ['City', 'text'], 'zip' => ['Zip', 'text'], 'esiid' => ['New ESIID', 'text'], 'date' => ['Move-in date', 'date']]],
            'change-plan' => ['Plan - Change Plan', []],
            'spend-stars' => ['MyAccount - Spend Stars', []],
            'reset-login' => ['MyAccount - Reset Login', []],
            'add-authorized-user' => ['MyAccount - Add Authorized User', ['name' => ['Name', 'text'], 'phone' => ['Phone', 'text']]],
            'send-email' => ['Contact - Send Email', ['template' => ['Template', 'template'], 'message' => ['Message', 'textarea']]],
            'send-text' => ['Contact - Send Text', ['message' => ['Message', 'textarea']]],
            'test-meter' => ['Meter - Test Meter', []],
            'reread' => ['Meter - ReRead', []],
            'request-usage' => ['Meter - Request Usage', []],
        ],
    ],

    // Products that can be on an account, and the model name each is logged under
    'products' => [
        'AutoPay' => 'ItemProductAutopay_model',
        'Paperless Billing' => 'ItemProductPaperless_model',
        'Rangler Rewards' => 'ItemProductReward_model',
        'Peak Perks' => 'ItemProductPeakPerk_model',
        'Peak Perks+' => 'ItemProductPeakPerksPlus_model',
        'Giddyup Guarantee' => 'ItemProductGiddyup_model',
        'Freedom Flex' => 'ItemProductFreedomFix_model',
        'Solar Buyback' => 'ItemProductSolar_model',
        'Solar Lead Referral' => 'ItemProductLeadSolar_model',
        'Deposit Alternatives' => 'ItemProductDepositAlt_model',
        'Payment Arrangement' => 'ItemProductPaymentArrangement_model',
        'Deferred Payment Plan' => 'ItemProductDeferredPayment_model',
        'Balanced Billing' => 'ItemProductBalancedBilling_model',
        'Combined Billing' => 'ItemProductCombinedBilling_model',
        'AIG Home Warranty' => 'ItemProductWarrantyHome_model',
        'Electric System Protection Program' => 'ItemProductWarrantyLine_model',
        'Surge Protection Program' => 'ItemProductWarrantySurge_model',
        'Air Conditioning Protection Program' => 'ItemProductWarrantyAc_model',
        'Electric Vehicle Charger Protection Program' => 'ItemProductWarrantyCharger_model',
        'ecobee' => 'ItemProductThermostat_model',
        'Pick Your Due Date' => 'ItemProductDueDate_model',
        'Refer-A-Friend' => 'ItemProductReferral_model',
        'ADT Security' => 'ItemProductAdt_model',
    ],

    // Products that also switch a yes/no field on the account
    'product_fields' => ['AutoPay' => 'autopay', 'Paperless Billing' => 'paperless', 'Peak Perks' => 'peak_perks'],

    'note_categories' => [
        'Agent Issue' => ['Audio Issue', 'Customer Disconnect/Hang up', 'Customer Not Authorized', 'Internal Transfer', 'Problem with System', 'Test', 'Wrong Number'],
        'Billing' => ['Balance Inquiry', 'Balanced Billing Inquiry', 'Balanced Billing Set up', 'Bill Not Received', 'Billing Dispute', 'DNP/RNP', 'Fees', 'PYDD/Due Date Change', 'Rate', 'Resend Bill', 'Usage', 'Waive Deposit/Fee'],
        'Complaint' => ['Billing', 'Customer Service', 'Deposit Refund', 'Disconnection', 'PA/DPP', 'Provision of Service', 'Rates', 'Sales Misinformation', 'Slamming', 'Solar Buy Back'],
        'Inquiry' => ['Contract Inquiry', 'Outage', 'Update Contact Info'],
        'MVO/Cancel/Rescission' => ['Cancel - Changed Mind', 'Cancel - Contract', 'Cancel - Not Moving to Address', 'Cancel - Price', 'MVO', 'Rescission'],
        'Order' => ['Change Plan', 'Date Change', 'Deposit Waiver Docs', 'General Inquiry', 'Link Accounts', 'Meter/ESI Inquiry', 'Military/First Responder', 'MT Request/Status', 'New Enrollment', 'Re-run Credit', 'Reject/Rejection', 'Renewal', 'Status Inquiry', 'Switch Hold', 'Transfer of Service', 'Verify ID'],
        'Payment' => ['AutoPay Set Up', 'Deposit Refund Request', 'DPP Set Up', 'Duplicate Payment/Refund', 'Missing Payment', 'PA/DPP/Extension Inquiry', 'Pay Deposit', 'Payment Arrangement Set up', 'Payment Dispute', 'Payment Made', 'Pledge Inquiry', 'Remove Autopay'],
        'Products' => ['Add ecobee', 'Add Freedom Flex', 'Add Home Warranty', 'Add Peak Perks/Plus', 'Add Solar Buy Back', 'Ecobee Inquiry', 'Refer A Friend (RAF)', 'Remove ecobee', 'Remove Freedom Flex', 'Remove Home Warranty', 'Remove Paperless Billing', 'Remove Peak Perks/Plus', 'Remove Solar Buy Back', 'Solar BuyBack Inquiry'],
        'Rewards' => ['Gift Card', 'Promo Code', 'Redeem Stars'],
        'Website/Mobile' => ['Cannot Log in', 'Online Issue', 'Reset Username/Password'],
    ],

    'priorities' => ['Low', 'Medium', 'High'],

    // Spend Stars offers: [stars, offer, description, effect]. effect: credit:<amount> | gift | drawing | product:<name>
    'reward_offers' => [
        [0, 'Monthly Drawing', 'Enter this month\'s drawing.', 'drawing'],
        [50, '$10 Bill Credit', 'Redeem 50 stars for $10 off the next bill.', 'credit:10'],
        [100, '$25 Bill Credit', 'Redeem 100 stars for a $25 bill credit.', 'credit:25'],
        [100, '$25 Starbucks Gift Card', 'Redeem 100 stars for a $25 Starbucks e-gift card.', 'gift'],
        [100, '$25 Amazon Gift Card', 'Redeem 100 stars for a $25 Amazon e-gift card.', 'gift'],
        [100, '$25 Target Gift Card', 'Redeem 100 stars for a $25 Target e-gift card.', 'gift'],
        [150, '$50 Bill Credit', 'Redeem 150 stars for a $50 bill credit.', 'credit:50'],
        [150, '$50 Starbucks Gift Card', 'Redeem 150 stars for a $50 Starbucks e-gift card.', 'gift'],
        [150, '$50 Amazon Gift Card', 'Redeem 150 stars for a $50 Amazon e-gift card.', 'gift'],
        [150, '$50 Target Gift Card', 'Redeem 150 stars for a $50 Target e-gift card.', 'gift'],
        [450, 'Free Month of Electricity', '450 stars for a bill credit of up to $150.', 'credit:150'],
        [600, 'ecobee Smart Thermostat', 'Redeem 600 stars for an ecobee smart thermostat.', 'product:ecobee'],
    ],

    'email_templates' => [
        'Welcome Letter', 'Welcome Letter - Renewed', 'Renewal - Confirmation', 'Billing - Resi - Payment Made', 'Payment Made',
        'Bill Ready', 'MyAcct - Peak Perks - Welcome to Peak Perks', 'Freedom Flex - Confirmation', 'MyAccount - Password Reset',
        'Winback Offer', 'Disconnect Notice', 'Custom Message',
    ],

    // Every queue an account can be moved into (TECH → Move Queues)
    'queues' => [
        'QueueBillComplete',
        'QueueBillException',
        'QueueBillReady',
        'QueueBillUnprocessed',
        'QueueBill',
        'QueueCallStart',
        'QueueCall',
        'QueueCartAbandon',
        'QueueCartAccepted',
        'QueueCartActive',
        'QueueCartAddOrder',
        'QueueCartArchive',
        'QueueCartAutopayRequired',
        'QueueCartBalancedBilling',
        'QueueCartBalancedue',
        'QueueCartBillReady',
        'QueueCartBlendExtend',
        'QueueCartCancel',
        'QueueCartCollection',
        'QueueCartDead',
        'QueueCartDeposit',
        'QueueCartDisconnectComplete',
        'QueueCartDisconnectNotice',
        'QueueCartDisconnectRejected',
        'QueueCartDisconnectSent',
        'QueueCartDisconnect',
        'QueueCartDropped',
        'QueueCartDropping',
        'QueueCartDualfuel',
        'QueueCartExceptionBalance',
        'QueueCartExceptionCancelled',
        'QueueCartExceptionChangeRenew',
        'QueueCartExceptionCommercialMatrix',
        'QueueCartExceptionCommercial',
        'QueueCartExceptionDuplicate',
        'QueueCartExceptionEmailDropped',
        'QueueCartExceptionErcotCancel',
        'QueueCartExceptionErcotDatechange',
        'QueueCartExceptionErcotDisconnect',
        'QueueCartExceptionErcotEnrollment',
        'QueueCartExceptionErcotMoveout',
        'QueueCartExceptionErcotOther',
        'QueueCartExceptionErcotReconnect',
        'QueueCartExceptionErcot',
        'QueueCartExceptionEsiid',
        'QueueCartExceptionFraud',
        'QueueCartExceptionMultiple',
        'QueueCartExceptionOther',
        'QueueCartExceptionPermitRequired',
        'QueueCartExceptionPlan',
        'QueueCartExceptionProvisional',
        'QueueCartExceptionSuspect',
        'QueueCartExceptionSwitchHold',
        'QueueCartExceptionTest',
        'QueueCartExceptionTransfer',
        'QueueCartExceptionUnprocessed',
        'QueueCartException',
        'QueueCartFulfilledAccepted',
        'QueueCartFulfilledCancelledDropped',
        'QueueCartFulfilledCancelled',
        'QueueCartFulfilledChurned',
        'QueueCartFulfilledDepositPaid',
        'QueueCartFulfilledDeposit',
        'QueueCartFulfilledDocusign',
        'QueueCartFulfilledFlowing',
        'QueueCartFulfilledHold',
        'QueueCartFulfilledImport',
        'QueueCartFulfilledOutboxHold',
        'QueueCartFulfilledOutbox',
        'QueueCartFulfilledPending',
        'QueueCartFulfilledRejectedAutopay',
        'QueueCartFulfilledRejectedCredit',
        'QueueCartFulfilledRejectedError',
        'QueueCartFulfilledRejectedExisting',
        'QueueCartFulfilledRejectedFrozen',
        'QueueCartFulfilledRejectedPermitRequired',
        'QueueCartFulfilledRejectedPlan',
        'QueueCartFulfilledRejectedSwitchhold',
        'QueueCartFulfilledRejectedTransfer',
        'QueueCartFulfilledRejectedUan',
        'QueueCartFulfilledRejected',
        'QueueCartFulfilledRequested',
        'QueueCartFulfilled',
        'QueueCartMeterMvo',
        'QueueCartMeterRead',
        'QueueCartMeterReconnect',
        'QueueCartMeterTest',
        'QueueCartMeter',
        'QueueCartMvo',
        'QueueCartPassthru',
        'QueueCartPaymentArrangementDefaulted',
        'QueueCartPromoApplied',
        'QueueCartReconnectComplete',
        'QueueCartReconnectRejected',
        'QueueCartReconnectSent',
        'QueueCartReconnect',
        'QueueCartReturnedmail',
        'QueueCartStart',
        'QueueCartSubmit',
        'QueueCartSwitchhold',
        'QueueCartSystemdown',
        'QueueCartTextCancelled',
        'QueueCartText',
        'QueueCartTransition',
        'QueueCartUsagerequest',
        'QueueCartVipBilling',
        'QueueCartVipCriticalcare',
        'QueueCartVipDeferredpayment',
        'QueueCartVipFriendsandfamily',
        'QueueCartVipIag',
        'QueueCartVipIal',
        'QueueCartVipOther',
        'QueueCartVipPaymentarrangement',
        'QueueCartVipPuc',
        'QueueCartVip',
        'QueueCartWinbackComplete',
        'QueueCartWinbackSent',
        'QueueCartWinback',
        'QueueCartWriteoff',
        'QueueCart',
        'QueueForecastComplete',
        'QueueForecastProcessing',
        'QueueForecastStart',
        'QueueForecast',
        'QueueLedgerPending',
        'QueueLedgerSent',
        'QueueLedgerSkipped',
        'QueueLedger',
        'QueueMyaccountHidden',
        'QueueMyaccountPlanChanged',
        'QueueMyaccountPlanRenewed',
        'QueueMyaccountTransferred',
        'QueueMyaccount',
        'QueueOfferRateAccepted',
        'QueueOfferRatePending',
        'QueueOfferRate',
        'QueueOffer',
        'QueuePartnerDeposit',
        'QueuePartnerProvisional',
        'QueuePartnerSherpa',
        'QueuePartnerWhitelisted',
        'QueuePartner',
        'QueueProductCombinedBilling',
        'QueueProductDepositAlt',
        'QueueProductFreedomFixComplete',
        'QueueProductFreedomFixReady',
        'QueueProductFreedomFix',
        'QueueProductGiddyupAccepted',
        'QueueProductGiddyupExpired',
        'QueueProductGiddyupPending',
        'QueueProductGiddyupReady',
        'QueueProductGiddyupRejected',
        'QueueProductGiddyup',
        'QueueProductSolar',
        'QueueProduct',
        'Queue',
    ],
];
